=== xavi-mat/producto3-final/base.dtd
<!ELEMENT contenido (tema+)>
<!ATTLIST contenido
  xmlns CDATA #FIXED ''>

<!ELEMENT tema (texto?,subtema*)>
<!ATTLIST tema
  xmlns CDATA #FIXED ''
  titulo CDATA #REQUIRED
  id CDATA #REQUIRED>

<!ELEMENT subtema (texto?,apartado*)>
<!ATTLIST subtema
  xmlns CDATA #FIXED ''
  titulo CDATA #REQUIRED
  id CDATA #REQUIRED>

<!ELEMENT apartado (texto?,subapartado*)>
<!ATTLIST apartado
  xmlns CDATA #FIXED ''
  titulo CDATA #REQUIRED
  id CDATA #REQUIRED>

<!ELEMENT subapartado (texto)>
<!ATTLIST subapartado
  xmlns CDATA #FIXED ''
  titulo CDATA #REQUIRED
  id CDATA #REQUIRED>

<!ELEMENT texto (#PCDATA|saltolinea|code|codeblock|lista|negrita|cursiva|enlace|tabla)*>
<!ATTLIST texto
  xmlns CDATA #FIXED ''>

<!ELEMENT saltolinea EMPTY>

<!ELEMENT code (#PCDATA)>

<!ELEMENT codeblock (#PCDATA)>

<!ELEMENT lista (item+)>
<!ELEMENT item (#PCDATA|negrita|cursiva|code|codeblock|saltolinea|tabulador)*>

<!ELEMENT negrita (#PCDATA)>

<!ELEMENT cursiva (#PCDATA)>

<!ELEMENT enlace (#PCDATA)>
<!ATTLIST enlace
  xmlns CDATA #FIXED ''
  referencia CDATA #REQUIRED>

<!ELEMENT tabla (fila+)>
<!ELEMENT fila (celda+)>
<!ELEMENT celda (#PCDATA|negrita|cursiva)*>

=== xavi-mat/producto3-final/base.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contenido SYSTEM "base.dtd">
<contenido>
  <tema id="1" titulo="1. Lenguajes de marcas">
    <texto>Existen desde el comienzo de la informática. Son lenguajes sencillos para el intercambio de información entre distintos sistemas. Con la irrupción de internet, alguno de estos lenguajes son piedras angulares sobre las que construir World Wide Web. Existen gran variedad de lenguajes de marcas, más o menos importantes, pero comparten elementos comunes: fundamentos, orígenes, características básicas y elementos relacionados con su estructura.</texto>
    <subtema id="1_a" titulo="a. ¿Qué son los lenguajes de marcas?">
      <texto>
        Es aquel que permite representar información que contiene, además de los datos propiamente dichos, marcas o etiquetas que indican cómo se estructuran estos datos, su significado o cómo debe representarse desde un punto de vista gráfico o visual. No son lenguajes de programación, es decir no contienen instrucciones ni implican acciones directas. Son reglas que organizan la información con objeto de dar una estructura uniforme y facilitar su procesamiento automático.
        <saltolinea />
        Se distinguen:
        <lista>
          <item>Lenguajes orientados a la presentación de información</item>
          <item>Lenguajes orientados al almacenamiento y proceso de información.</item>
        </lista>
      </texto>
    </subtema>
    <subtema id="1_b" titulo="b. Ejemplos de lenguajes de marcas">
      <texto>La web y las aplicaciones desarrolladas sobre la tecnología de internet, supuso un importante incremento en el uso de los lenguajes de marcas, tanto para representar información como para intercambiar datos entre sistemas. Los lenguajes de marcas poseen una utilidad importante, como puede ser la configuración de aplicaciones o la definición de interfaces gráficas de usuario.</texto>
      <apartado id="1_b_i" titulo="i. HTML">
        <texto>Es el lenguaje de marcas más conocido y utilizado, y el W3C se encarga de su mantenimiento y estandarización. La versión HTML5 se publicó en octubre de 2014 y supuso un cambio radical y muy exitoso en el lenguaje. El objetivo principal es proporcionar un mecanismo para diseñar páginas web que van a ser presentadas en un navegador, ya sea este ejecutado en un ordenador, en una videoconsola o en un dispositivo móvil. Para el diseño gráfico cuenta con una capacidad ilimitada de elementos de maquetación gracias al uso conjunto con las hojas de estilo en cascada (CSS). W3C World Wide Web Consortium, fue creado en octubre de 1994, con el objetivo de definir estándares para internet. La extensión de sus ficheros HTML suele ser, .html o .htm.</texto>
      </apartado>
      <apartado id="1_b_ii" titulo="ii. XML">
        <texto>
          El lenguaje de marcado extensible es el lenguaje de intercambio de información entre sistemas por excelencia. Se dice que XML es para los sistemas el equivalente a HTML para los humanos. Puede servir para almacenar la configuración de una aplicación, los mejores marcadores de un videojuego, el diseño de una interfaz de usuario o la información de un gráfico vectorial. La primera versión salió en 1998, al igual que HTML, una especificación del W3C y se define como "de propósito general". Esto significa que es un metalenguaje al venir definido por reglas y no por etiquetas concretas.
          <saltolinea />
          La extensión de sus ficheros XML suele ser .xml
        </texto>
      </apartado>
      <apartado id="1_b_iii" titulo="iii. XHTML">
        <texto>
          Se puede definir de manera simplificada como la versión en formato XML del lenguaje de marcas HTML. Se presentó en el año 2000 como una recomendación del W3C.
          <saltolinea />
          XHTML tiene la misma relación con XML que HTML con SGML. Tanto HTML como XHTML surgen a partir de un metalenguaje y ambos son lenguajes de marcado para el desarrollo de las páginas web.
        </texto>
      </apartado>
      <apartado id="1_b_iv" titulo="iv. SVG">
        <texto>Scalable Vector Graphics o gráficos vectoriales escalables, es un dialecto de XML. Se utiliza para representar gráficos vectoriales de dos dimensiones. La extensión de los ficheros SVG suele ser .svg o .svgz.</texto>
      </apartado>
      <apartado id="1_b_v" titulo="v. MathML">
        <texto>Mathematical Markup Language o lenguaje de marcado matemático, es un dialecto de XML. Se utiliza para representar notaciones matemáticas.</texto>
      </apartado>
      <apartado id="1_b_vi" titulo="vi. NewsML">
        <texto>NewsML (News Markup Language o lenguaje de marcado de noticias) es un dialecto XML. Se utiliza para representar noticias electrónicas.</texto>
      </apartado>
      <apartado id="1_b_vii" titulo="vii. FXML">
        <texto>Es un dialecto de xml. Se emplea para representar las interfaces de usuario en la tecnología JavaFX del lenguaje de programación Java.</texto>
      </apartado>
      <apartado id="1_b_viii" titulo="viii. XAML">
        <texto>XAML (eXtensible Application Markup Language o lenguaje de marcado extensible de aplicación). Es un dialecto de XML. Es el lenguaje en el que se definen las interfaces de usuario en las aplicaciones para el sistema operativo Windows desarrolladas con la tecnología de Microsoft.</texto>
      </apartado>
      <apartado id="1_b_ix" titulo="ix. Android">
        <texto>En las aplicaciones de Android, la forma habitual de diseñar las interfaces de usuario es mediante ficheros escritos en dialecto de XML. En estos ficheros se definen los esquemas de distribución, así como los componentes y sus características que van a permitir al usuario interactuar con la aplicación.</texto>
      </apartado>
      <apartado id="1_b_x" titulo="x. Servicios Web">
        <texto>
          Un servicio web (web services) es un componente software alojado en un servidor al que se accede utilizando protocolos estándares y tecnologías de la web como HTTP, HTTPS, XML o JSON.
          <saltolinea />
          Los denominados servicios RESTful (también llamados REST) utilizan con frecuencia dialectos de XML (en otras muchas ocasiones usan JSON) para el intercambio de información entre los dos puntos de la comunicación.
        </texto>
      </apartado>
      <apartado id="1_b_xi" titulo="xi. RSS y Atom">
        <texto>Tanto RSS (Really Simple Syndication o Sindicación realmente simple) como Atom son dialectos de XML. Se utilizan para la distribución de contenidos de fuentes a los que los usuarios se han suscrito previamente, siendo Atom una alternativa a RSS creado con posterioridad.</texto>
      </apartado>
      <apartado id="1_b_xii" titulo="xii. XSL">
        <texto>XSL (eXtensible Stylesheet Language o lenguaje de hojas de estilo extensible) es una especificación del W3C utilizada para transformar y manipular documentos XML. Permite indicar cómo ha de presentarse la información contenida en un documento XML.</texto>
      </apartado>
    </subtema>
  </tema>
  <tema id="2" titulo="2. eXtensible Markup language (XML)">
    <subtema id="2_a" titulo="a. Definición de XML">
      <texto>
        Es un lenguaje de marcado que define un conjunto de reglas para codificar documentos. El lenguaje XML proporciona una plataforma para definir elementos para crear formatos y generar lenguaje personalizado.
        <saltolinea />
        El archivo XML se divide en dos partes: prolog y body. El prolog consta de metadatos de gestión, como declaraciones XML, instrucciones de procesamiento opcionales, declaraciones de tipo de documento y comentarios. Por otro lado, el cuerpo consta de dos partes: estructura y contenido (presente en texto simple).
        <saltolinea />
        El diseño XML se centra en la simplicidad, la versatilidad y la facilidad de uso, por lo que se utiliza en varios servicios web. Tanto es así que existen sistemas diseñados para ayudar a definir lenguajes basados en XML y API para ayudar a procesar datos XML, que no deben confundirse con HTML.
        <saltolinea />
      </texto>
    </subtema>
    <subtema id="2_b" titulo="b. Utilidades de XML">
      <texto>
        Algunos de sus usos más extendidos son:
        <saltolinea />
        <lista>
          <item>
            <negrita>Intercambiar datos entre sistemas:</negrita>
            uno de los objetivos básicos de XML es permitir que los datos se intercambien entre diferentes sistemas de forma estructurada. Como formato de texto plano y lenguaje estandarizado, hace que esta transmisión sea muy flexible e independiente de la plataforma utilizada.
          </item>
          <item>
            <negrita>Base de datos:</negrita>
            uno de los objetivos básicos de XML es permitir que los datos se intercambien entre diferentes sistemas de forma estructurada. Como formato de texto plano y lenguaje estandarizado, hace que esta transmisión sea muy flexible e independiente de la plataforma utilizada.
          </item>
          <item>
            <negrita>Convertir:</negrita>
            actualmente son muchos los formatos que ofrecen servicios de conversión a XML, como PDF, HTML, .text, .docx o XHTML
          </item>
        </lista>
      </texto>
    </subtema>
    <subtema id="2_c" titulo="c. Estructura de documentos XML">
      <texto>
        XML es una estructura para definir lenguajes, por eso se afirma que XML es un
        <cursiva>metalenguaje</cursiva>
        .
        <saltolinea />
        Como el objetivo de los documentos XML es transportar datos con su significado, cada documento XML debe hacer referencia a dos realidades, los datos y los significados. Los datos serán textos simples incluidos en el documento XML pero, ¿cómo reconoce el ordenador el significado de esos datos?
        <saltolinea />
